# =============================================================================
# Fish Shell Configuration
# Generated by dev-setup
# Based on: https://skippingpetticoatconvent.github.io/
# =============================================================================

if status is-interactive

    # -----------------------------------------------------------------------------
    # Welcome message
    # -----------------------------------------------------------------------------
    set -g fish_greeting ""

    # -----------------------------------------------------------------------------
    # Environment variables
    # -----------------------------------------------------------------------------
    set -gx EDITOR nvim
    set -gx VISUAL $EDITOR
    set -gx PAGER less

    # XDG Base Directory
    set -gx XDG_CONFIG_HOME $HOME/.config
    set -gx XDG_DATA_HOME $HOME/.local/share
    set -gx XDG_CACHE_HOME $HOME/.cache

    # -----------------------------------------------------------------------------
    # PATH configuration
    # -----------------------------------------------------------------------------
    # Rust
    if test -d $HOME/.cargo/bin
        fish_add_path $HOME/.cargo/bin
    end

    # Go
    if test -d /usr/local/go/bin
        fish_add_path /usr/local/go/bin
    end
    set -gx GOPATH $HOME/go
    if test -d $GOPATH/bin
        fish_add_path $GOPATH/bin
    end

    # Python (uv)
    if test -d $HOME/.local/bin
        fish_add_path $HOME/.local/bin
    end

    # Bun
    if test -d $HOME/.bun
        set -gx BUN_INSTALL "$HOME/.bun"
        fish_add_path $BUN_INSTALL/bin
    end

    # fnm (Node.js)
    if test -d $HOME/.fnm
        fnm env --use-on-cd | source
    end

    # Ollama
    if test -d $HOME/.ollama
        set -gx OLLAMA_HOST 0.0.0.0:11434
    end

    # -----------------------------------------------------------------------------
    # Fisher plugins initialization
    # -----------------------------------------------------------------------------
    # Set fzf keybindings
    set -gx FZF_DEFAULT_OPTS '
        --color=bg+:#323232,bg:#1e1e1e,spinner:#fcb68a,hl:#d3859b
        --color=fg:#d4d4d4,header:#d3859b,pointer:#fcb68a,marker:#fcb68a
    '
    set -gx FZF_CTRL_T_OPTS "--preview 'bat --color=always --style=header --line-range=:100 {}'"
    set -gx FZF_CTRL_R_OPTS "--preview 'echo {}' --preview-window down:3:hidden:wrap"

    # -----------------------------------------------------------------------------
    # Abbreviations (shortcuts)
    # -----------------------------------------------------------------------------
    # Git
    abbr -a g git
    abbr -a gs git status
    abbr -a ga git add
    abbr -a gc git commit
    abbr -a gp git push
    abbr -a gl git pull
    abbr -a gb git branch
    abbr -a gco git checkout
    abbr -a gd git diff
    abbr -a gca git commit --amend

    # System
    abbr -a ll ls -lah
    abbr -a la ls -A
    abbr -a l ls -CF

    # Docker
    abbr -a d docker
    abbr -a dc docker-compose
    abbr -a dsp docker system prune -af
    abbr -a dlo docker logs
    abbr -a dex docker exec -it

    # tmux
    abbr -a t tmux
    abbr -a ta tmux attach
    abbr -a tl tmux list-sessions
    abbr -a tk tmux kill-session

    # Python
    abbr -a py python3
    abbr -a uvpy python3 -m uv

    # Navigation
    abbr -a .. cd ..
    abbr -a ... cd ../..
    abbr -a .... cd ../../..

    # -----------------------------------------------------------------------------
    # Aliases
    # -----------------------------------------------------------------------------
    # grep with colors
    if type -q grep
        alias grep grep --color=auto
    end

    # Improved cat
    if type -q bat
        alias cat bat
    end

    # Improved ls
    if type -q eza
        alias ls eza --icons --group-directories-first
        alias ll eza -l --icons --group-directories-first
        alias la eza -la --icons --group-directories-first
        alias lt eza --tree --level=2 --icons
    else if type -q exa
        alias ls exa --icons --group-directories-first
        alias ll exa -l --icons --group-directories-first
        alias la exa -la --icons --group-directories-first
    else
        alias ls ls --color=auto
    end

    # Neovim
    if type -q nvim
        alias vim nvim
        alias vi nvim
    end

    # curl headers
    alias curli 'curl -I'

    # -----------------------------------------------------------------------------
    # Functions
    # -----------------------------------------------------------------------------

    # Create directory and cd into it
    function mkcd
        mkdir -p $argv[1]; and cd $argv[1]
    end

    # Extract various archive formats
    function extract
        if test (count $argv) -eq 0
            echo "Usage: extract <file>"
            return 1
        end
        
        set -l file $argv[1]
        
        if test -f $file
            switch $file
                case *.tar.bz2
                    tar xjf $file
                case *.tar.gz
                    tar xzf $file
                case *.bz2
                    bunzip2 $file
                case *.rar
                    unrar x $file
                case *.gz
                    gunzip $file
                case *.tar
                    tar xf $file
                case *.tbz2
                    tar xjf $file
                case *.tgz
                    tar xzf $file
                case *.zip
                    unzip $file
                case *.Z
                    uncompress $file
                case *.7z
                    7z x $file
                case *
                    echo "Unknown archive format"
                    return 1
            end
        else
            echo "File not found: $file"
            return 1
        end
    end

    # Find file by name
    function ff
        find . -type f -iname "*$argv*"
    end

    # Find directory by name
    function fd
        find . -type d -iname "*$argv*"
    end

    # Kill process by name
    function kp
        ps aux | grep $argv | grep -v grep | awk '{print $2}' | xargs kill -9
    end

    # Copy to clipboard
    if type -q xclip
        alias cpy 'xclip -selection clipboard'
    end

    # -----------------------------------------------------------------------------
    # Starship prompt initialization
    # -----------------------------------------------------------------------------
    if type -q starship
        starship init fish | source
    end

end
