# =============================================================================
# Zsh Configuration
# Generated by dev-setup
# Based on: https://skippingpetticoatconvent.github.io/
# =============================================================================

# -----------------------------------------------------------------------------
# Oh My Zsh configuration
# -----------------------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"

# Set theme
ZSH_THEME="robbyrussell"

# Enable plugins (order matters!)
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-history-substring-search
    fzf
)

# -----------------------------------------------------------------------------
# User configuration
# -----------------------------------------------------------------------------
export LANG=en_US.UTF-8

# Set default editor
export EDITOR=nvim
export VISUAL=nvim

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# -----------------------------------------------------------------------------
# PATH configuration
# -----------------------------------------------------------------------------
# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Go
export GOPATH="$HOME/go"
export GOROOT="/usr/local/go"
export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"

# Python (uv)
export PATH="$HOME/.local/bin:$PATH"

# Bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# fnm
export PATH="$HOME/.fnm:$PATH"
eval "$(fnm env --use-on-cd)"

# Ollama
export OLLAMA_HOST=0.0.0.0:11434

# -----------------------------------------------------------------------------
# Aliases
# -----------------------------------------------------------------------------
# Git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gb='git branch'
alias gco='git checkout'
alias gd='git diff'
alias gca='git commit --amend'

# System
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'

# Docker
alias d='docker'
alias dc='docker-compose'
alias dsp='docker system prune -af'
alias dlo='docker logs'
alias dex='docker exec -it'

# tmux
alias t='tmux'
alias ta='tmux attach'
alias tl='tmux list-sessions'
alias tk='tmux kill-session'

# Python
alias py='python3'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Improved commands
alias grep='grep --color=auto'

# Neovim
if command -v nvim &>/dev/null; then
    alias vim='nvim'
    alias vi='nvim'
fi

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------

# Create directory and cd into it
mkcd() {
    mkdir -p "$1" && cd "$1"
}

# Extract various archive formats
extract() {
    if [[ $# -eq 0 ]]; then
        echo "Usage: extract <file>"
        return 1
    fi
    
    local file="$1"
    
    if [[ -f "$file" ]]; then
        case "$file" in
            *.tar.bz2) tar xjf "$file" ;;
            *.tar.gz) tar xzf "$file" ;;
            *.bz2) bunzip2 "$file" ;;
            *.rar) unrar x "$file" ;;
            *.gz) gunzip "$file" ;;
            *.tar) tar xf "$file" ;;
            *.tbz2) tar xjf "$file" ;;
            *.tgz) tar xzf "$file" ;;
            *.zip) unzip "$file" ;;
            *.Z) uncompress "$file" ;;
            *.7z) 7z x "$file" ;;
            *) echo "Unknown archive format" && return 1 ;;
        esac
    else
        echo "File not found: $file"
        return 1
    fi
}

# Find file by name
ff() {
    find . -type f -iname "*$1*"
}

# Find directory by name
fd() {
    find . -type d -iname "*$1*"
}

# Kill process by name
kp() {
    ps aux | grep "$1" | grep -v grep | awk '{print $2}' | xargs kill -9
}

# -----------------------------------------------------------------------------
# Starship prompt
# -----------------------------------------------------------------------------
if command -v starship &>/dev/null; then
    eval "$(starship init zsh)"
fi

# -----------------------------------------------------------------------------
# Load completion
# -----------------------------------------------------------------------------
autoload -Uz compinit
compinit
