# =============================================================================
# fzf keybindings for Fish
# Generated by dev-setup
# =============================================================================

# Setup fzf key bindings
# Ctrl-R: Search command history
# Ctrl-T: Search files in current directory
# Alt-C:  cd into selected directory

# Use fd instead of find
set -g FZF_CTRL_T_COMMAND "fd --type f --hidden --follow --exclude .git"
set -g FZF_CTRL_T_OPTS "
    --preview 'bat --color=always --style=header --line-range=:100 {}'
    --bind 'ctrl-/:toggle-preview'
    --layout=reverse
    --height=80%"

# Search command history
set -g FZF_CTRL_R_OPTS "
    --preview 'echo {}'
    --preview-window down:3:hidden:wrap
    --layout=reverse
    --height=80%"

# cd into selected directory
set -g FZF_ALT_C_COMMAND "fd --type d --hidden --follow --exclude .git"
set -g FZF_ALT_C_OPTS "
    --preview 'ls -la {}'
    --layout=reverse
    --height=80%"
