# =============================================================================
# fzf keybindings for Zsh
# Generated by dev-setup
# =============================================================================

# Setup fzf key bindings
# Ctrl-R: Search command history
# Ctrl-T: Search files in current directory
# Alt-C:  cd into selected directory

# Use fd instead of find
export FZF_CTRL_T_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_CTRL_T_OPTS="
    --preview 'bat --color=always --style=header --line-range=:100 {}'
    --bind 'ctrl-/:toggle-preview'
    --layout=reverse
    --height=80%"

# Search command history
export FZF_CTRL_R_OPTS="
    --preview 'echo {}'
    --preview-window down:3:hidden:wrap
    --layout=reverse
    --height=80%"

# cd into selected directory
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"
export FZF_ALT_C_OPTS="
    --preview 'ls -la {}'
    --layout=reverse
    --height=80%"

# Key bindings
__fzf_select__() {
    local cmd="${FZF_CTRL_T_COMMAND:-"find . -maxdepth 5"}"
    eval "$cmd" | fzf --multi | while read -r item; do
        printf '%q ' "$item"
    done
    echo
}

__fzf_history__() {
    local selected
    selected=$(fc -l 1 | fzf --no-height --tac +s +m | sed 's/ *[0-9]* *//')
    if [[ -n "$selected" ]]; then
        BUFFER="$selected"
        CURSOR=$#BUFFER
    fi
    zle redisplay
}

__fzf_cd__() {
    local cmd="${FZF_ALT_C_COMMAND:-"find . -type d"}"
    local dir
    dir=$(eval "$cmd" | fzf --no-height +m) && cd "$dir"
    zle reset-prompt
}

zle -N __fzf_select__
zle -N __fzf_history__
zle -N __fzf_cd__

bindkey '^R' __fzf_history__
bindkey '^T' __fzf_select__
bindkey '\ec' __fzf_cd__
